const CONSTANTS = {
  THEMES: {
    LIGHT:"LIGHT",
    DARK:"DARK"
  },
  LANGUAGE:{
    UKRAINIAN: "UKRAINIAN",
    RUSSIAN: "RUSSIAN",
  },
  MENU_ACTIONS:{
    MENU_OPEN:"MENU_OPEN",
    MENU_CLOSE:"MENU_CLOSE",
  }
};


export default CONSTANTS